### ISSUE TITLE
shading failure on JDK 24

### ISSUE THREAD

**Issue by jakub-id** [apache/maven-shade-plugin#747]
### Affected version

3.6.0

### Bug description

On JDK 24 with `minimizeJar=true` shading errors with:

`Error creating shaded jar: Unsupported class file major version 68`

Bumping ASM dependency to 9.8 does not fix the problem. Please release a new version which support JDK24 and JDK25.

**Comment by olamy** [comment]
done via https://github.com/apache/maven-shade-plugin/pull/749 
haha so groovy has his shaded asm, jdependency has his shaded asm. someone else? :)

**Comment by olamy** [comment]
arghh right `org.vafer:jdependency:2.13` is jdk 11 minimum :(

**Comment by Gaibhne** [comment]
I attempted to work around this in `3.6.0` by forcing the `jdependency:2.13` dependency, but that alone was not enough, the update to `asm:9.8` was also needed. Only with both forced dependencies I was able to compile with 24. `asm-commons:9.8` isn't needed, but it'd probably be a bad idea to have a mismatch there.

**Comment by olamy** [comment]
> I attempted to work around this in `3.6.0` by forcing the `jdependency:2.13` dependency, but that alone was not enough, the update to `asm:9.8` was also needed. Only with both forced dependencies I was able to compile with 24. `asm-commons:9.8` isn't needed, but it'd probably be a bad idea to have a mismatch there.

yes both are needed.  asm in the plugin itself is already done via https://github.com/apache/maven-shade-plugin/pull/744
but this one we cannot really  upgrade except making the plugin jdk11 required. 
Personnally I would not mind but this might generate some discussions

**Comment by tcurdt** [comment]
> done via [#749](https://github.com/apache/maven-shade-plugin/pull/749) haha so groovy has his shaded asm, jdependency has his shaded asm. someone else? :)

As long as they are minimized - no real harm done :)


I still have this in my inbox.

Nothing I can help with I guess?
Just waiting for a new release of the maven-shade-plugin? What's blocking that?
